name: HTB to Notion

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Import HTB Machines to Notion
        run: ./htb-notion.py --htb-token {{ secrets.HTB_APP_TOKEN }} --notion-token ${{ secrets.NOTION_API_KEY }} --notion-db ${{ secrets.NOTION_DB_ID }}